[tool.poetry]
name = "{{ cookiecutter.__package_name }}"
version = "0.1.0"
description = ""
license = "{% if cookiecutter.license == 'ASL' %}Apache-2.0{% elif cookiecutter.license == 'BSD3' %}BSD-3-Clause{% elif cookiecutter.license == 'MIT' %}MIT{% endif %}"
readme = "README.md"
authors = ["{{ cookiecutter.author }} <{{ cookiecutter.email }}>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pre-commit = "^4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
